server:
  port: 9030
  servlet.context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/intelligence_db
    username: ${PSQL_USER}
    password: ${PSQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  ai:
    model.chat: openai
    openai:
      api-key: ${AI_API_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: google/gemini-3-flash-preview
          temperature: 0.2
      embedding:
        options:
          model: qwen/qwen3-embedding-8b

---

spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://pgvector.lovable-core.svc.cluster.local:5432/intelligence_db
    username: intelligence_user
    password: ${DB_PASSWORD}
  ai:
    model.chat: openai
    openai:
      api-key: ${AI_API_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: google/gemini-3-flash-preview
          temperature: 0.2
